### ISSUE TITLE
Making `client.api_key` and `client.api_url` private

### ISSUE THREAD

**Issue by mertssmnoglu** [wdonofrio/lemonsqueezy-py-api#1]
Hello. First of all thanks for this :lemon: Lemon Squeezy library.

Just a friendly tip, client class's `api_key` and `api_url` properties can be private with `__` prefix. It would be more useful for the developer.

I want to work on this.

**Comment by wdonofrio** [comment]
Hi @mertssmnoglu.

Thank you! And thanks for the feedback.

I actually reviewed the `api_key` and `api_url` properties of the class, and believe they weren't even used properly. Functionality was enabled through the config.py and __init__.py files. This was due to the client object coming in much later in my development.

As a result, I deprecated this logic and fully embraced the client object. As the prefixes were a simple addition, I handled this as well. However, please don't let this discourage future contributions! This is my first SDK, so I'm open to any feedback or direct contributions!
